name: Static analysis

on: [pull_request]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        # Additional apt packages that need to be installed before running Cmake
        apt_pckgs: libyaml-cpp-dev libsnappy-dev
        cppcheck_args: --enable=all --suppressions-list=../.cppcheck-suppressions.txt --inline-suppr --inconclusive --error-exitcode=1
