name: Static analysis

on: [pull_request]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        # Additional apt packages that need to be installed before running Cmake
        apt_pckgs: libyaml-cpp-dev libsnappy-dev
        cppcheck_args: --enable=all --suppress=duplicateBranch --inline-suppr --inconclusive --error-exitcode=1
        cmake_args: -DMINIMAL=true

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cc: clang
        cxx: clang
        build-type: Release
        # Extra options pass to cmake while configuring project
        configure-options: -DMINIMAL=true
        run-test: true
        install-build: false
        # run build using '-j [parallel]' to use multiple threads to build
        parallel: 2
